version: "3.9"

services:
  app:
    image: auth:1.0
    ports:
      - "8080:8080"
    depends_on:
      - redis
    network_mode: host

  redis:
    image: redis:7.0
    ports:
      - "6379:6379"
    network_mode: host
